---
- hosts: localhost
  connection: local
  become: true

  tasks:

# ################################
# apt-get update && apt-get upgrade
# ################################

  - name: 'apt-get: updating and upgrading'
    ansible.builtin.apt:
      force_apt_get: yes
      upgrade: yes
      update_cache: yes

# ################################
# locale-gen and localectl
# ################################

  - name: 'locale-gen: fr_FR (ISO-8859-1)'
    community.general.locale_gen:
      state: present
      name: fr_FR

  - name: 'locale-gen: fr_FR.UTF-8'
    community.general.locale_gen:
      state: present
      name: fr_FR.UTF-8

  - name: 'locale-gen: en_US (ISO-8859-1)'
    community.general.locale_gen:
      state: present
      name: en_US

  - name: 'locale-gen: en_US.UTF-8'
    community.general.locale_gen:
      state: present
      name: en_US.UTF-8

  - name: 'localectl: configure locale and language'
    ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8 LANGUAGE=en_US

  - name: 'localectl: set-x11-keymap'
    ansible.builtin.command: localectl set-x11-keymap fr

# ################################
# ubuntu-desktop
# ################################

  - name: 'apt packages: install ubuntu-desktop'
    ansible.builtin.package:
      state: present
      name: ubuntu-desktop

# ################################
# users
# ################################

  - name: 'users: creating "etienneg"'
    ansible.builtin.user:
      state: present
      name: "{{ item }}"
      shell: /bin/bash
      append: yes
      groups: adm,cdrom,sudo,dip,plugdev,lpadmin,lxd
      password: '$6$bc.dsTpAG4tmqRK6$o8dO2F8vjgOTWvykliZst04Iwp./Dl1MLHxfrFEJ0XVQCnwP2kUFGb.33ADvq5Y0gq0WXYANOQZuer22NXxx90'
      update_password: on_create
    loop:
      - etienneg
    # register: users_forced_to_change_password
    # notify: change password

  - name: 'users: creating "ansible-deploy"'
    ansible.builtin.user:
      state: present
      name: ansible-deploy
      system: yes
      shell: /bin/false

# ################################
# system config
# ################################

  - name: 'system config: disabling Wayland and setting Xorg as default display server'
    ansible.builtin.copy:
      src: files/etc/gdm3/custom.conf
      dest: /etc/gdm3/custom.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: 'system config: restarting gdm3 service'
    ansible.builtin.service:
      state: restarted
      name: gdm3

# ################################
# apt packages
# ################################

  - name: 'apt packages: install CLI development tools'
    ansible.builtin.package:
      state: present
      name:
        - jq
        - tree
        - shellcheck
        - libsecret-tools
        - python3-pip

  - name: 'apt packages: install GUI development tools'
    ansible.builtin.package:
      state: present
      name:
        - virtualbox
        - rabbitvcs-nautilus

# ################################
# snap packages
# ################################

  - name: 'snap packages: install GUI development tools'
    ansible.builtin.snap:
      state: present
      name:
        - code
        - notepadqq
        # - docker

  - name: 'snap packages: install desktop tools'
    ansible.builtin.snap:
      state: present
      name:
        - brave
        - blueman
        - teams
        # - teams / teams-for-linux

# ################################
# users config
# ################################

  - name: 'users config: adding user "ansible-deploy" to sudoers list'
    ansible.builtin.copy:
      src: files/etc/sudoers.d/ansible-deploy
      dest: /etc/sudoers.d/ansible-deploy
      owner: root
      group: root
      mode: 0440

  - name: 'users config: adding ansible-pull cron job for user "ansible-deploy"'
    ansible.builtin.cron:
      state: present
      name: 'ansible auto-provision'
      user: ansible-deploy
      minute: '*/10'
      job: ansible-pull -o -U https://github.com/etiennegaschet/ansible_ubuntu-desktop-22.04.1-lts.git

# ################################
# apt-get autoclean && apt-get autoremove && apt-get clean
# ################################

  - name: 'apt-get autoclean: remove useless packages from the cache'
    ansible.builtin.apt:
      force_apt_get: yes
      autoclean: yes

  - name: 'apt-get autoremove: remove dependencies that are no longer required'
    ansible.builtin.apt:
      force_apt_get: yes
      autoremove: yes

  - name: 'apt-get clean: '
    ansible.builtin.apt:
      force_apt_get: yes
      clean: yes

# ################################
# handlers
# ################################

  # handlers:
  #   - name: 'handlers: forcing new users to change their password on first login'
  #     shell: chage -d 0 {{ item.name }}
  #     loop: "{{ users_forced_to_change_password.results }}"
  #     when: item.changed
  #     listen: change password
