---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: 'creating user: etienneg'
    user:
      state: present
      name: "{{ item }}"
      shell: /bin/bash
      append: yes
      groups: adm,cdrom,sudo,dip,plugdev,lpadmin,lxd
      password: '$6$bc.dsTpAG4tmqRK6$o8dO2F8vjgOTWvykliZst04Iwp./Dl1MLHxfrFEJ0XVQCnwP2kUFGb.33ADvq5Y0gq0WXYANOQZuer22NXxx90'
      update_password: on_create
    loop:
      - etienneg
    register: users_forced_to_change_password
    notify: change password

  - name: 'creating user: ansible-deploy'
    user:
      state: present
      name: ansible-deploy
      system: yes
      shell: /bin/false

  - name: 'adding ansible-deploy user to sudoers list'
    copy:
      src: files/etc/sudoers.d/ansible-deploy
      dest: /etc/sudoers.d/ansible-deploy
      owner: root
      group: root
      mode: 0440

  - name: 'adding ansible-pull cron job for user ansible-deploy'
    cron:
      name: 'ansible auto-provision'
      user: ansible-deploy
      minute: '*/10'
      job: ansible-pull -o -U https://github.com/etiennegaschet/ansible_ubuntu-desktop-22.04.1-lts.git

  - name: 'install ubuntu-desktop'
    package:
      name: ubuntu-desktop

  - name: 'disabling Wayland and setting Xorg as default display server'
    copy:
      src: files/etc/gdm3/custom.conf
      dest: /etc/gdm3/custom.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: 'restarting gdm3 service'
    service:
      name: gdm3
      state: restarted

  - name: install jq
    package:
      name:
        - jq

  # - name: install shellcheck
  #   package:
  #     name:
  #       - shellcheck

  # - name: install CLI tools
  #   package:
  #     name:
  #       - jq
  #       - libsecret-tools
  #       - shellcheck
  #       - python3-pip

  # - name: install Desktop tools
  #   package:
  #     name:
  #       - 

  # - name: install Desktop tools via snap
  #   package:
  #     name:
  #       - blueman

  handlers:
    - name: 'forcing new users to change their password on first login'
      shell: chage -d 0 {{ item.name }}
      loop: "{{ users_forced_to_change_password.results }}"
      when: item.changed
      listen: change password