---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: 'creating user: etienneg'
    user:
      state: present
      name: etienneg
      shell: /bin/bash
      append: yes
      groups: adm,cdrom,sudo,dip,plugdev,lxd
      password: '$6$bc.dsTpAG4tmqRK6$o8dO2F8vjgOTWvykliZst04Iwp./Dl1MLHxfrFEJ0XVQCnwP2kUFGb.33ADvq5Y0gq0WXYANOQZuer22NXxx90'
      # update_password: on_create

  # #
  # # run 'chage -d 0 myusername' command for newly created users only, so they are forced to change their password:
  # # https://serverfault.com/questions/1106276/ansible-how-to-run-subsequent-task-for-only-newly-created-users
  # #
  # - name: force change password
  #   command: 'chage -d 0 etienneg'
  #   when: item.changed
  #   loop: "{{ accounts.results }}"

  - name: 'creating user: ansible-deploy'
    user:
      state: present
      name: ansible-deploy
      system: yes
      shell: /bin/false

  - name: 'adding ansible-deploy user to sudoers list'
    copy:
      src: files/etc/sudoers.d/ansible-deploy
      dest: /etc/sudoers.d/ansible-deploy
      owner: root
      group: root
      mode: 0440

  - name: 'adding ansible-pull cron job for user ansible-deploy'
    cron:
      name: 'ansible auto-provision'
      user: ansible-deploy
      minute: '*/10'
      job: ansible-pull -o -U https://github.com/etiennegaschet/ansible_ubuntu-desktop-22.04.1-lts.git

  - name: 'install ubuntu-desktop'
    package:
      name: ubuntu-desktop

  - name: 'disabling Wayland and setting Xorg as default display server'
    copy:
      src: files/etc/gdm3/custom.conf
      dest: /etc/gdm3/custom.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: 'restarting gdm3 service'
    service:
      name: gdm3
      state: restarted

  # - name: install jq
  #   package:
  #     name:
  #       - jq

  # - name: install CLI tools
  #   package:
  #     name:
  #       - jq
  #       - libsecret-tools
  #       - shellcheck
  #       - python3-pip

  # - name: install Desktop tools
  #   package:
  #     name:
  #       - 

  # - name: install Desktop tools via snap
  #   package:
  #     name:
  #       - blueman
